export {HomeScreen} from "./homeScreen"
export {LoginScreen} from "./loginScreen"
export {HistoryScreen} from "./historyScreen"
export {AnalysisScreen} from "./analysisScreen"
export { RegisterScreen } from "./registerScreen"